// Generated by dia2code
#ifndef RENDER__EDITEUR__H
#define RENDER__EDITEUR__H

#include <string>
#include <vector>
#include <memory>

namespace render {
  class RenduCarte;
}

#include "RenduCarte.h"

namespace render {

  /// class Editeur - 
  class Editeur {
    // Associations
    // Attributes
  private:
    int dimX;
    int dimY;
    int sizeX;
    int sizeY;
    int ind_dbt;
    int nb_elem;
    bool isVertical;
    std::string nom;
    std::vector<RenduCarte> listeCartes;
    // Operations
  public:
    Editeur (string nom);
    std::weak_ptr<Etat::Objet> Click ();
    void Draw (sf::RenderTarget& target);
    void Actu (std::vector<std::weak_ptr<Objet> > list_carte);
    int GetDimX () const;
    int GetDimY () const;
    int GetSizeX () const;
    int GetSizeY () const;
    int GetIndDbt () const;
    int GetNbElem () const;
    bool GetIsVertical () const;
    std::string GetNom () const;
    std::Vector<RenduCarte> GetCartes () const;
    void SetIndDbt (int value);
    // Setters and Getters
  };

};

#endif
