// Generated by dia2code
#ifndef RENDER__EDITEUR__H
#define RENDER__EDITEUR__H

#include <string>
#include <vector>
#include <memory>

namespace Render {
  class RenduCarte;
}

#include "RenduCarte.h"

namespace Render {

  /// class Editeur - 
  class Editeur {
    // Associations
    // Attributes
  private:
    int x;
    int y;
    int width;
    int height;
    int ind_dbt;
    int nb_elem;
    bool isVertical;
    std::string nom;
    std::vector<RenduCarte> listeCartes;
    // Operations
  public:
    Editeur (std::string nom, bool orientation, int x, int y, int width, int height);
    std::weak_ptr<Etat::Objet> Click ();
    void Draw (sf::RenderTarget& target);
    void Actu (std::vector<std::weak_ptr<Etat::Objet> > list_carte);
    int GetX () const;
    int GetY () const;
    int GetWidth () const;
    int GetHeight () const;
    int GetIndDbt () const;
    int GetNbElem () const;
    bool GetIsVertical () const;
    std::string GetNom () const;
    std::Vector<RenduCarte> GetCartes () const;
    void SetIndDbt (int value);
    // Setters and Getters
  };

};

#endif
