// Generated by dia2code
#ifndef RENDER__EDITEUR__H
#define RENDER__EDITEUR__H

#include <string>
#include <vector>
#include <memory>

namespace Render {
  class RenduCarte;
}

#include "RenduCarte.h"


namespace Render {

  /// class Editeur - 
  class Editeur {
    // Associations
    // Attributes
  private:
    int x;
    int y;
    int width;
    int height;
    int ind_dbt;
    int nb_elem;
    bool isVertical;
    sf::Text nom;
    std::vector<std::shared_ptr<Etat::Objet> >  listeCartes;
    std::vector<sf::Sprite> spriteCarte;
    sf::Sprite b1;
    sf::Sprite b2;
    // Operations
  public:
    Editeur (std::string nom, bool orientation, int x, int y, int width, int height);
    Etat::Objet Click ();
    void Draw (sf::RenderTarget& target);
    void Actu (std::vector<std::shared_ptr<Etat::Objet> >  list_carte);
    int GetX () const;
    int GetY () const;
    int GetWidth () const;
    int GetHeight () const;
    int GetIndDbt () const;
    int GetNbElem () const;
    bool GetIsVertical () const;
    std::string GetNom () const;
    std::vector<std::shared_ptr<Etat::Objet> > GetCartes () const;
    void SetIndDbt (int value);
    // Setters and Getters
  };

};

#endif
