// Generated by dia2code
#ifndef RENDER__RENDU__H
#define RENDER__RENDU__H

#include <memory>

namespace Render {
  class Editeur;
}

#include "Editeur.h"

namespace Render {

  /// class Rendu - 
  class Rendu {
    // Associations
    // Attributes
  private:
    int dimensionX;
    int dimensionY;
    Editeur cimetiere1;
    Editeur cimetiere2;
    Editeur bf21;
    Editeur bf22;
    Editeur stack;
    Editeur bf12;
    Editeur bf11;
    Editeur hand;
    Editeur listCapa;
    std::shared_ptr<Etat::State> state;
    std::shared_ptr<Etat::Objet> selectedCard;
    
    sf::Sprite sprite;
    
    sf::Text txt_etat;
    sf::Text txt_nomSelect;
    sf::Text txt_Oracle;
    sf::Text txt_instruction;
    
    sf::Texture texture;
    sf::Font font;
    // Operations
  public:
    Rendu (std::shared_ptr<Etat::State> etat, int x, int y);
    void Click (int x, int y);
    void Draw (sf::RenderTarget&  target);
    //void Actu ();
    Editeur GetGrv1 () const;
    Editeur GetGrv2 () const;
    Editeur GetBf11 () const;
    Editeur GetBf12 () const;
    Editeur GetStack () const;
    Editeur GetBf21 () const;
    Editeur GetBf22 () const;
    Editeur GetHand () const;
    int GetDimX () const;
    int GetDimY () const;
    // Setters and Getters
  };

};

#endif
