// Generated by dia2code
#ifndef ETAT__CAPACITE__H
#define ETAT__CAPACITE__H


namespace Etat {
  class Objet;
}

#include "Objet.h"

namespace Etat {

  /// class Capacite - 
  class Capacite : public Etat::Objet {
    // Attributes
  protected:
    string keyWord;
    int categorie;
    // Operations
  public:
    String GetKeyWord ();
    int GetCategorie ();
    Capacite ();
    ~Capacite ();
    // Setters and Getters
    const string& getKeyWord() const;
    void setKeyWord(const string& keyWord);
    int getCategorie() const;
    void setCategorie(int categorie);
  };

};

#endif
