// Generated by dia2code
#ifndef ETAT__CAPACITE__H
#define ETAT__CAPACITE__H


namespace Etat {
  class Objet;
}

#include "Objet.h"

namespace Etat {

  /// class Capacite - 
  class Capacite : public Etat::Objet {
    // Attributes
  protected:
    std::string keyWord;
    int categorie;
    // Operations
  public:
    std::string GetKeyWord ();
    int GetCategorie ();
    Capacite (std::string motclef, int type);
    // Setters and Getters
//    const string& getKeyWord() const;
//    void setKeyWord(const string& keyWord);
//    int getCategorie() const;
//    void setCategorie(int categorie);
  };

};

#endif
