// Generated by dia2code
#ifndef ETAT__CREATURE__H
#define ETAT__CREATURE__H


namespace Etat {
  class Carte;
}

#include "Carte.h"

namespace Etat {

  /// class Creature - 
  class Creature : public Etat::Carte {
    // Attributes
  private:
    int force;
    int endurance;
    int bonusEOT;
    int blessure;
    bool malInvoc;
    // Operations
  public:
    int GetForce ();
    int GetEndurance ();
    void SetBonusEOT ();
    void SetBlessure ();
    bool GetMalInvoc ();
    void SetMalInvoc (bool value);
    Creature ();
    ~Creature ();
    // Setters and Getters
  };

};

#endif
