// Generated by dia2code
#ifndef ETAT__DECLENCHEE__H
#define ETAT__DECLENCHEE__H


namespace Etat {
  class Capacite;
}

#include "Capacite.h"

namespace Etat {

  /// class Declenchee - 
  class Declenchee : public Etat::Capacite {
    // Operations
  public:
    void EventHandler (int value);
    Declenche ();
    ~Declenche ();
    // Setters and Getters
  };

};

#endif
