// Generated by dia2code
#ifndef ETAT__ETAT__H
#define ETAT__ETAT__H


namespace Etat {
  class Joueur;
  class Zone;
  class Objet;
}

#include "Zone.h"
#include "Joueur.h"
#include "Objet.h"

namespace Etat {

  /// class Etat - 
  class Etat {
    // Associations
    // Attributes
  private:
    int joueur;
    int phase;
    Joueur * joueurs;
    int priorite;
    Zone pile;
    Zone battlefield;
    int nbJoueur;
    // Operations
  public:
    void IncrPriority ();
    void IncrPhase ();
    Joueur JoueurActif ();
    void ToPile (Objet obj);
    void ToBattlefield (Objet obj);
    Joueur GetJoueur (int i);
    Etat (int nb = 2);
    ~Etat ();
    // Setters and Getters
  };

};

#endif
