// Generated by dia2code
#ifndef ETAT__ETAT__H
#define ETAT__ETAT__H

#include <vector>

namespace Etat {
  class Joueur;
  class Objet;
}

#include "Objet.h"
#include "Joueur.h"

namespace Etat {

  /// class Etat - 
  class Etat {
    // Associations
    // Attributes
  private:
    int joueur;
    int phase;
    Joueur * joueurs;
    int priorite;
    std::vector<Objet> pile;
    std::vector<Objet> battlefield;
    int nbJoueur;
    // Operations
  public:
    void IncrPriority ();
    void IncrPhase ();
    Joueur JoueurActif ();
    void AddCardPile (Objet card);
    void AddCardBattlefield (Objet card);
    Etat (int nb = 2);
    int GetNbJoueur ();
    ~Etat ();
    Joueur GetJoueur (int i);
    void DelCardBattlefield (Objet card);
    void DelCardPile (Objet card);
    std::vector<Objet> GetPile ();
    std::vector<Objet> GetBattlefield ();
    // Setters and Getters
  };

};

#endif
