// Generated by dia2code
#ifndef ETAT__JOUEUR__H
#define ETAT__JOUEUR__H

namespace Etat {
  class ManaPool;
  class Zone;
  class Objet;
  class Carte;
  class Active;
}

#include "ManaPool.h"
#include "Zone.h"
#include "Carte.h"
#include "Active.h"
#include "Objet.h"

namespace Etat {

  /// class Joueur - 
  class Joueur {
    // Associations
    // Attributes
  private:
    ManaPool manaPool;
    int pv;
    bool aJoueTerrain;
    Zone graveyard;
    Zone hand;
    Zone library;
    Objet* cartes;
    int nbCarte;
    // Operations
  public:
    int GetPv ();
    void SetPv (int Pv);
    void Draw ();
    void Discard ();
    void Sacrifice (Objet carte);
    Zone GetHand ();
    Zone GetLibrary ();
    Zone GetGraveyard ();
    ManaPool GetManaPool();
    bool GetAJoueTerrain ();
    void SetAJoueTerrain (bool value);
    Objet GetCarte (int i);
    Joueur ();
    ~Joueur ();
    void AddObjet (Objet newObj);
    void DestroyObjet(Objet Obj);
    int GetNbCarte();
    // Setters and Getters
  };

};

#endif
