// Generated by dia2code
#ifndef ETAT__JOUEUR__H
#define ETAT__JOUEUR__H

#include <vector>

namespace Etat {
  class ManaPool;
  class Objet;
}

#include "ManaPool.h"
#include "Objet.h"

namespace Etat {

  /// class Joueur - 
  class Joueur {
    // Associations
    // Attributes
  private:
    ManaPool manaPool;
    int pv;
    bool aJoueTerrain;
    std::vector<Objet> hand;
    std::vector<Objet> graveyard;
    std::vector<Objet> library;
    // Operations
  public:
    int GetPv ();
    void SetPv (int Pv);
    void Draw ();
    void Discard ();
    std::vector<Objet> GetHand ();
    bool GetAJoueTerrain ();
    void SetAJoueTerrain (bool value);
    Joueur ();
    ~Joueur ();
    std::vector<Objet> GetLibrary ();
    std::vector<Objet> GetGraveyard ();
    ManaPool GetManaPool ();
    void AddCardLibrary (Objet card);
    void AddCardHand (Objet card);
    void AddCardGraveyard (Objet card);
    void DelCardHand (Objet card);
    void DelCardLibrary (Objet card);
    void DelCardGraveyard (Objet card);
    // Setters and Getters
  };

};

#endif
