// Generated by dia2code
#ifndef ETAT__MANAPOOL__H
#define ETAT__MANAPOOL__H


namespace Etat {
  class Cout;
}

#include "Cout.h"

namespace Etat {

  /// class ManaPool - 
  class ManaPool {
    // Attributes
  private:
     int inc;
     int black;
     int blue;
     int green;
     int multi;
    // Operations
  public:
    void AddInc ();
    void AddBlue ();
    void AddBlack ();
    void AddGreen ();
    void AddMulti ();
    void Vider ();
    void Payer (Cout cost);
    int GetInc ();
    int GetBlue ();
    int GetBlack ();
    int GetGreen ();
    int GetMulti ();
    // Setters and Getters
  };

};

#endif
