// Generated by dia2code
#ifndef ETAT__OBJET__H
#define ETAT__OBJET__H


namespace Etat {
  class Zone;
  class Objet;
}

#include "Zone.h"

namespace Etat {

  /// class Objet - 
  class Objet {
    // Attributes
  protected:
    bool isCapacite;
    Zone conteneur;
    Objet target;
    // Operations
  public:
    virtual void Resolve () = 0;
    void SetTarget (Objet cible);
    Objet GetTarget ();
    bool GetIsCapacite ();
    Zone GetConteneur ();
    void Deplacer (Zone zoneCible);
    // Setters and Getters
    bool getIsCapacite() const;
    void setIsCapacite(bool isCapacite);
    const Zone& getConteneur() const;
    void setConteneur(const Zone& conteneur);
    const Objet& getTarget() const;
    void setTarget(const Objet& target);
  };

};

#endif
