// Generated by dia2code
#ifndef RENDER__RENDU__H
#define RENDER__RENDU__H

#include <memory>
#include <SFML/Graphics.hpp>
#include <vector>

namespace Render {
  class Editeur;
};
namespace Etat {
  class State;
  class Objet;
}

#include "Editeur.h"
#include "Etat/State.h"
#include "Etat/Objet.h"

namespace Render {

  /// class Rendu - 
  class Rendu {
    // Associations
    // Attributes
  public:
    sf::Text nb;
  private:
    int dimensionX;
    int dimensionY;
    Editeur cimetiere1;
    Editeur cimetiere2;
    Editeur bf21;
    Editeur bf22;
    Editeur stack;
    Editeur bf12;
    Editeur bf11;
    Editeur hand;
    Editeur listCapa;
    std::shared_ptr<Etat::State> state;
    std::shared_ptr<Etat::Objet> selectedCard;
    sf::Sprite sprite;
    sf::Text txt_etat;
    sf::Text txt_nomSelect;
    sf::Text txt_Oracle;
    sf::Text txt_instruction;
    sf::Texture texture;
    sf::Font font;
    int joueur;
    sf::Texture ttMp;
    sf::Sprite mp;
    // Operations
  public:
    Rendu (std::shared_ptr<Etat::State> etat, int x, int y, int j);
    void Click (int x, int y);
    void Draw (sf::RenderTarget&  target);
    template<typename T> std::vector<std::shared_ptr<Etat::Objet> > Conv (std::vector<std::shared_ptr<T> > data);
    void DrawSelectedCard (sf::RenderTarget& target);
    void DrawManaPool (sf::RenderTarget& target, int i);
    void DrawBf (sf::RenderTarget& target, int joueur, Editeur& bf1, Editeur& bf2);
    // Setters and Getters
  };

};

#endif
