// Generated by dia2code
#ifndef AI__IA_DEEP__H
#define AI__IA_DEEP__H

#include <memory>
#include <vector>

namespace Etat {
  class State;
};
namespace Engine {
  class Moteur;
};
namespace Ai {
  class Ia_Heuristic;
}

#include "Etat/State.h"
#include "Engine/Moteur.h"
#include "Ia_Heuristic.h"

namespace Ai {

  /// class Ia_Deep - 
  class Ia_Deep : public Ai::Ia_Heuristic {
    // Operations
  public:
    Ia_Deep (std::shared_ptr<Etat::State> state, std::shared_ptr<Engine::Moteur> moteur);
    void Think ();
    void Attaque ();
    void Bloque ();
    std::vector<bool> ExtractBool (int val);
    void PlayLand ();
    // Setters and Getters
  };

};

#endif
