// Generated by dia2code
#ifndef AI__IA_HEURISTIC__H
#define AI__IA_HEURISTIC__H

#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Moteur;
};
namespace Ai {
  class Ia_Base;
}

#include "Etat/State.h"
#include "Engine/Moteur.h"
#include "Ia_Base.h"

namespace Ai {

  /// class Ia_Heuristic - 
  class Ia_Heuristic : public Ai::Ia_Base {
    // Operations
  public:
    Ia_Heuristic (std::shared_ptr<Etat::State> state, std::shared_ptr<Engine::Moteur> moteur);
    void Think ();
    int EvalState ();
    void DoBestAction ();
    void Retour (int val);
    bool TryCast (std::shared_ptr<Etat::Cout> cost);
    void FinTour ();
    void Attaque ();
    void Bloque ();
    // Setters and Getters
  };

};

#endif
