// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H

#include <vector>
#include <memory>

namespace Engine {
  class Command;
}

#include "Command.h"

namespace Engine {

  /// class AttackCommand - 
  class AttackCommand : public Engine::Command {
    // Attributes
  private:
    std::vector<std::shared_ptr<Etat::Creature> > attaquant;
    // Operations
  public:
    AttackCommand ();
    void AddAttaquant (std::shared_ptr<Etat::Creature> crea);
    void Execute (Etat::State& state);
    // Setters and Getters
  };

};

#endif
