// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H

#include <vector>
#include <memory>

namespace Etat {
  class Creature;
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/Creature.h"
#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class AttackCommand - 
  class AttackCommand : public Engine::Command {
    // Associations
    // Attributes
  private:
    std::vector<std::shared_ptr<Etat::Creature> > attaquant;
    // Operations
  public:
    void AddAttaquant (std::shared_ptr<Etat::Creature> crea);
    void Execute (std::shared_ptr<Etat::State> state);
    void SupprAttaquant (std::shared_ptr<Etat::Creature> crea);
    // Setters and Getters
  };

};

#endif
