// Generated by dia2code
#ifndef ENGINE__BLOCKCOMMAND__H
#define ENGINE__BLOCKCOMMAND__H

#include <vector>
#include <memory>

namespace Etat {
  class Creature;
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/Creature.h"
#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class BlockCommand - 
  class BlockCommand : public Engine::Command {
    // Associations
    // Attributes
  private:
    std::vector<std::shared_ptr<Etat::Creature> > bloqueur;
    std::vector<std::shared_ptr<Etat::Creature> > bloque;
    // Operations
  public:
    void AddBloqueur (std::shared_ptr<Etat::Creature> bloqueur, std::shared_ptr<Etat::Creature> bloque);
    void Execute (std::shared_ptr<Etat::State> state);
    void SupprBloqueur (std::shared_ptr<Etat::Creature> crea);
    // Setters and Getters
  };

};

#endif
