// Generated by dia2code
#ifndef ENGINE__BLOCKCOMMAND__H
#define ENGINE__BLOCKCOMMAND__H

#include <vector>
#include <memory>

namespace Engine {
  class Command;
}

#include "Command.h"

namespace Engine {

  /// class BlockCommand - 
  class BlockCommand : public Engine::Command {
    // Attributes
  private:
    std::vector<std::shared_ptr<Etat::Creature> > crea_bloque;
    std::vector<std::shared_ptr<Etat::Creature> > bloqueur;
    // Operations
  public:
    BlockCommand ();
    void AddBloqueur (std::shared_ptr<Etat::Creature> bloqueur, std::shared_ptr<Etat::Creature> bloque);
    void Execute (Etat::State& state);
    // Setters and Getters
  };

};

#endif
