// Generated by dia2code
#ifndef ENGINE__COMMANDSOLVECOMBAT__H
#define ENGINE__COMMANDSOLVECOMBAT__H

#include <vector>
#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandSolveCombat - vide les liste d'attaquants et de bloqueurs et inflige les degats
  class CommandSolveCombat : public Engine::Command {
    // Associations
    // Attributes
  private:
    std::vector<int> idAttaquants;
    std::vector<int> idBloqueur;
    std::vector<int> idBloque;
    // Operations
  public:
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
