// Generated by dia2code
#ifndef ENGINE__COMMANDDIE__H
#define ENGINE__COMMANDDIE__H

#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandDie - 
  class CommandDie : public Engine::Command {
    // Associations
    // Attributes
  private:
    int idCarte;
    int idProp;
    // Operations
  public:
    CommandDie (std::shared_ptr<Etat::Carte> carte);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
