// Generated by dia2code
#ifndef ENGINE__COMMANDPAYE__H
#define ENGINE__COMMANDPAYE__H

#include <memory>
#include <json/json.h>

namespace Etat {
  class State;
};
namespace Engine {
  class CommandPaye;
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandPaye - 
  class CommandPaye : public Engine::Command {
    // Associations
    // Attributes
  private:
    int coutB, coutU, coutG, coutI, coutPv;
    int mB, mU, mG, mI, mM;
    bool hasWork;
    // Operations
  public:
    CommandPaye (std::shared_ptr<Etat::Cout> cout);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    Json::Value Serialize () const;
    CommandPaye* Deserialize (const Json::Value& in);
    CommandPaye ();
    // Setters and Getters
  };

};

#endif
