// Generated by dia2code
#ifndef ENGINE__COMMANDPHASE__H
#define ENGINE__COMMANDPHASE__H

#include <memory>
#include <json/json.h>

namespace Etat {
  class State;
};
namespace Engine {
  class CommandPhase;
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandPhase - 
  class CommandPhase : public Engine::Command {
    // Associations
    // Attributes
  private:
    int oldPhase;
    int newPhase;
    // Operations
  public:
    CommandPhase (int value);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    Json::Value Serialize () const;
    CommandPhase* Deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
