// Generated by dia2code
#ifndef ENGINE__COMMANDDRAW__H
#define ENGINE__COMMANDDRAW__H

#include <memory>
#include <json/json.h>

namespace Etat {
  class State;
};
namespace Engine {
  class CommandDraw;
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandDraw - 
  class CommandDraw : public Engine::Command {
    // Associations
    // Attributes
  private:
    int idJoueur;
    int idCarte;
    bool empty;
    // Operations
  public:
    CommandDraw (int id);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    Json::Value Serialize () const;
    CommandDraw* Deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
