// Generated by dia2code
#ifndef ENGINE__COMMANDCAST__H
#define ENGINE__COMMANDCAST__H

#include <memory>
#include <json/json.h>

namespace Etat {
  class State;
};
namespace Engine {
  class CommandCast;
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandCast - 
  class CommandCast : public Engine::Command {
    // Associations
    // Attributes
  private:
    int idCarte;
    int idJoueur;
    // Operations
  public:
    CommandCast (std::shared_ptr<Etat::Carte> carte);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    Json::Value Serialize () const;
    CommandCast* Deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
