// Generated by dia2code
#ifndef ENGINE__COMMANDTOUR__H
#define ENGINE__COMMANDTOUR__H

#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandTour - 
  class CommandTour : public Engine::Command {
    // Associations
    // Attributes
  private:
    int oldTour, newTour;
    // Operations
  public:
    CommandTour (int value);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
