// Generated by dia2code
#ifndef ENGINE__COMMANDCLEAN__H
#define ENGINE__COMMANDCLEAN__H

#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandClean - 
  class CommandClean : public Engine::Command {
    // Associations
    // Attributes
  private:
    int idCrea;
    int bonusEOT;
    int blessure;
    // Operations
  public:
    CommandClean (std::shared_ptr<Etat::Creature> crea);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
