// Generated by dia2code
#ifndef ENGINE__COMMANDRESOLVECARD__H
#define ENGINE__COMMANDRESOLVECARD__H

#include <memory>
#include <json/json.h>

namespace Engine {
  class Moteur;
};
namespace Etat {
  class State;
};
namespace Engine {
  class CommandResolveCard;
  class Command;
}

#include "Moteur.h"
#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandResolveCard - 
  class CommandResolveCard : public Engine::Command {
    // Associations
    // Attributes
  private:
    int idCarte;
    bool isPermanent;
    std::weak_ptr<Moteur> engine;
    int idProp;
    // Operations
  public:
    CommandResolveCard (std::shared_ptr<Etat::Carte> card, std::weak_ptr<Moteur> m);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    Json::Value Serialize () const;
    CommandResolveCard* Deserialize (const Json::Value& in);
    void SetEngine (std::weak_ptr<Engine::Moteur> moteur);
    CommandResolveCard ();
    // Setters and Getters
  };

};

#endif
