// Generated by dia2code
#ifndef ENGINE__COMMANDRESOLVECAPA__H
#define ENGINE__COMMANDRESOLVECAPA__H

#include <string>
#include <memory>
#include <json/json.h>

namespace Engine {
  class Moteur;
};
namespace Etat {
  class State;
};
namespace Engine {
  class CommandResolveCapa;
  class Command;
}

#include "Moteur.h"
#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandResolveCapa - 
  class CommandResolveCapa : public Engine::Command {
    // Associations
    // Attributes
  private:
    std::string keyWord;
    std::weak_ptr<Moteur> engine;
    int id_token, pos_target, indProp, idCapa, idTarget;
    // Operations
  public:
    CommandResolveCapa (std::shared_ptr<Etat::Capacite> capa, std::weak_ptr<Moteur> m);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    Json::Value Serialize () const;
    CommandResolveCapa* Deserialize (const Json::Value& in);
    void SetEngine (std::weak_ptr<Engine::Moteur> moteur);
    CommandResolveCapa ();
    // Setters and Getters
  };

};

#endif
