// Generated by dia2code
#ifndef ENGINE__COMMANDPRIORITY__H
#define ENGINE__COMMANDPRIORITY__H

#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandPriority - 
  class CommandPriority : public Engine::Command {
    // Associations
    // Attributes
  private:
    int oldPriority;
    int newPriority;
    // Operations
  public:
    CommandPriority (int value);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
