// Generated by dia2code
#ifndef ENGINE__COMMANDUNTAP__H
#define ENGINE__COMMANDUNTAP__H

#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandUntap - 
  class CommandUntap : public Engine::Command {
    // Associations
    // Attributes
  private:
    int idCarte;
    int hadMalInvoc;
    bool wasTaped;
    // Operations
  public:
    CommandUntap (std::shared_ptr<Etat::Carte> carte);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
