// Generated by dia2code
#ifndef ENGINE__COMMANDPAYE__H
#define ENGINE__COMMANDPAYE__H

#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandPaye - 
  class CommandPaye : public Engine::Command {
    // Associations
    // Attributes
  private:
    int coutB, coutU, coutG, coutI, coutPv;
    int mB, mU, mG, mI, mM;
    // Operations
  public:
    CommandPaye (std::shared_ptr<Etat::Cout> cout);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
