// Generated by dia2code
#ifndef ENGINE__COMMANDRESOLVECAPA__H
#define ENGINE__COMMANDRESOLVECAPA__H

#include <string>
#include <memory>

namespace Engine {
  class Moteur;
};
namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Moteur.h"
#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandResolveCapa - 
  class CommandResolveCapa : public Engine::Command {
    // Associations
    // Attributes
  private:
    std::string keyWord;
    std::weak_ptr<Moteur> engine;
    std::shared_ptr<Etat::Capacite> obj;
    std::shared_ptr<Etat::Objet> target;
    int id_token, pos_target;
    // Operations
  public:
    CommandResolveCapa (std::shared_ptr<Etat::Capacite> capa, std::weak_ptr<Moteur> m);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
