// Generated by dia2code
#ifndef ENGINE__COMMANDATTACK__H
#define ENGINE__COMMANDATTACK__H

#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandAttack - 
  class CommandAttack : public Engine::Command {
    // Associations
    // Attributes
  private:
    int idAttaquant;
    // Operations
  public:
    CommandAttack ( std::shared_ptr<Etat::Creature>);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
