// Generated by dia2code
#ifndef ENGINE__COMMANDACTIVE__H
#define ENGINE__COMMANDACTIVE__H

#include <string>
#include <memory>
#include <json/json.h>

namespace Etat {
  class State;
};
namespace Engine {
  class CommandActive;
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandActive - 
  class CommandActive : public Engine::Command {
    // Associations
    // Attributes
  private:
    int idSource;
    std::string keyWord;
    int idTarget;
    // Operations
  public:
    CommandActive (std::shared_ptr<Etat::Carte> carte, std::shared_ptr<Etat::Capacite> capa, std::weak_ptr<Etat::Objet> target);
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    Json::Value Serialize () const;
    CommandActive* Deserialize (const Json::Value& in);
    CommandActive ();
    // Setters and Getters
  };

};

#endif
