// Generated by dia2code
#ifndef ENGINE__COMMANDVIDEMP__H
#define ENGINE__COMMANDVIDEMP__H

#include <vector>
#include <memory>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class CommandVideMp - 
  class CommandVideMp : public Engine::Command {
    // Associations
    // Attributes
  private:
    std::vector<int> M, I, B, U, G;
    std::vector<bool> jt;
    // Operations
  public:
    void Execute (std::shared_ptr<Etat::State> state);
    void Undo (std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
