// Generated by dia2code
#ifndef ENGINE__LETPRIORITYCOMMAND__H
#define ENGINE__LETPRIORITYCOMMAND__H

#include <memory>
#include <string>

namespace Etat {
  class State;
};
namespace Engine {
  class Command;
}

#include "Etat/State.h"
#include "Command.h"

namespace Engine {

  /// class LetPriorityCommand - 
  class LetPriorityCommand : public Engine::Command {
    // Operations
  public:
    void Execute (std::shared_ptr<Etat::State> state);
    void Resolve (std::string keyword, std::shared_ptr<Etat::State> state);
    // Setters and Getters
  };

};

#endif
