// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H

#include <string>

namespace Engine {
  class Command;
}

#include "Command.h"

namespace Engine {

  /// class LoadCommand - 
  class LoadCommand : public Engine::Command {
    // Attributes
  public:
    std::string nom_fichier;
    // Operations
  public:
    LoadCommand (std::string deck1,std::string deck2);
    void Execute (Etat::State& state);
    // Setters and Getters
  };

};

#endif
