// Generated by dia2code
#ifndef ETAT__ACTIVE__H
#define ETAT__ACTIVE__H

#include <memory>
#include <string>

namespace Etat {
  class Cout;
  class Capacite;
}

#include "Cout.h"
#include "Capacite.h"

namespace Etat {

  /// class Active - 
  class Active : public Etat::Capacite {
    // Associations
    // Attributes
  private:
    std::shared_ptr<Cout> cost;
    // Operations
  public:
    Active (std::shared_ptr<Cout> cout, std::string motclef, int id, int prop, std::string nom, bool target);
    std::shared_ptr<Cout> GetCost () const;
    std::shared_ptr<Active> Clone ();
    // Setters and Getters
  };

};

#endif
