// Generated by dia2code
#ifndef ETAT__COUT__H
#define ETAT__COUT__H


namespace Etat {

  /// class Cout - 
  class Cout {
    // Attributes
  private:
    int inc;
    int black;
    int blue;
    int green;
    int life;
    // Operations
  public:
    Cout (int L, int I, int B, int U, int G);
    int GetLife () const;
    int GetInc () const;
    int GetBlue () const;
    int GetBlack () const;
    int GetGreen () const;
    // Setters and Getters
  };

};

#endif
