// Generated by dia2code
#ifndef ETAT__CREATURE__H
#define ETAT__CREATURE__H


namespace Etat {
  class Carte;
}

#include "Carte.h"

namespace Etat {

  /// class Creature - 
  class Creature : public Carte {
    // Attributes
  private:
    int force;
    int endurance;
    int bonusEOT;
    int blessure;
    bool malInvoc;
    // Operations
  public:
    int GetForce ();
    int GetEndurance ();
    int GetBlessure ();
    bool GetMalInvoc ();
    int GetBonusEOT ();
    
    void SetBonusEOT (int value);
    void SetBlessure (int value);
    void SetMalInvoc (bool value);
    Creature (int strengh, int thougness,bool token,std::string nom, Cout cout,
            Capacite capa, int id, int prop);
    
    // Setters and Getters
  };

};

#endif
