// Generated by dia2code
#ifndef ETAT__DECLENCHEE__H
#define ETAT__DECLENCHEE__H

#include <string>

namespace Etat {
  class Capacite;
}

#include "Capacite.h"

namespace Etat {

  /// class Declenchee - 
  class Declenchee : public Capacite {
    // Attributes
  private:
    int event;
    // Operations
  public:
    int GetEvent ();
    Declenchee (int evnt, std::string motclef, int id, int prop);
    // Setters and Getters
  };

};

#endif
