// Generated by dia2code
#ifndef ETAT__ETAT__H
#define ETAT__ETAT__H

#include <vector>

namespace Etat {
  class Joueur;
  class Objet;
  class Carte;
}

#include "Joueur.h"
#include "Objet.h"
#include "Carte.h"

namespace Etat {

  /// class Etat - 
  class Etat {
    // Associations
    // Attributes
  private:
    int joueur;
    int phase;
    Joueur * joueurs;
    int priorite;
    std::vector<Objet*> pile;
    std::vector<Carte*> battlefield;
    int nbJoueur;
    // Operations
  public:
    void IncrPriority ();
    void IncrPhase ();
    Joueur JoueurActif ();
    void AddCardPile (Objet card);
    void AddCardBattlefield (Carte card);
    Etat (int nb = 2);
    int GetNbJoueur ();
    Joueur GetJoueur (int i);
    void DelCardBattlefield (Carte card);
    void DelCardPile (Objet card);
    std::vector<Objet*> GetPile ();
    std::vector<Carte*> GetBattlefield ();
    // Setters and Getters
  };

};

#endif
