// Generated by dia2code
#ifndef ETAT__JOUEUR__H
#define ETAT__JOUEUR__H

#include <vector>

namespace Etat {
  class ManaPool;
  class Carte;
  class Objet;
}

#include "ManaPool.h"
#include "Carte.h"
#include "Objet.h"

namespace Etat {

  /// class Joueur - 
  class Joueur {
    // Associations
    // Attributes
  private:
    ManaPool manaPool;
    int pv;
    bool aJoueTerrain;
    std::vector<Carte*> hand;
    std::vector<Carte*> graveyard;
    std::vector<Carte*> library;
    // Operations
  public:
    int GetPv ();
    void SetPv (int Pv);
    void Draw ();
    void Discard ();
    std::vector<Carte*> GetHand ();
    bool GetAJoueTerrain ();
    void SetAJoueTerrain (bool value);
    Joueur ();
    std::vector<Carte*> GetLibrary ();
    std::vector<Carte*> GetGraveyard ();
    ManaPool GetManaPool ();
    void AddCardLibrary (Carte card);
    void AddCardHand (Carte card);
    void AddCardGraveyard (Carte card);
    void DelCardHand (Carte card);
    void DelCardLibrary (Carte card);
    void DelCardGraveyard (Carte card);
    // Setters and Getters
  };

};

#endif
