// Generated by dia2code
#ifndef ETAT__MANAPOOL__H
#define ETAT__MANAPOOL__H


namespace Etat {

  /// class ManaPool - 
  class ManaPool {
    // Attributes
  private:
    int inc;
    int black;
    int blue;
    int green;
    int multi;
    // Operations
  public:
    void SetInc (int value);
    void SetBlue (int value);
    void SetBlack (int value);
    void SetGreen (int value);
    void SetMulti (int value);
    int GetInc () const;
    int GetBlue () const;
    int GetBlack () const;
    int GetGreen () const;
    int GetMulti () const;
    // Setters and Getters
  };

};

#endif
