// Generated by dia2code
#ifndef ETAT__OBJET__H
#define ETAT__OBJET__H


namespace Etat {
  class Objet;
}


namespace Etat {

  /// class Objet - 
  class Objet {
    // Attributes
  private:
    bool isCapacite;
    Objet* target;
    int indJoueur;
    int idObj;

    // Operations
  public:
    void SetTarget (Objet cible);
    Objet GetTarget ();
    bool GetIsCapacite ();
    int GetIndJoueur ();
    int GetIdObj();
    
    Objet(bool capa, int id, int prop);
    
    // Setters and Getters
//    bool getIsCapacite() const;
//    void setIsCapacite(bool isCapacite);
//    const Objet& getTarget() const;
//    void setTarget(const Objet& target);
//    int getIndJoueur() const;
//    void setIndJoueur(int indJoueur);
  };

};

#endif
