// Generated by dia2code
#ifndef SERVER__COMMANDSERVICE__H
#define SERVER__COMMANDSERVICE__H

#include <memory>
#include <json/json.h>

namespace Engine {
  class Moteur;
};
namespace server {
  class AbstractService;
}

#include "Engine/Moteur.h"
#include "HttpStatus.h"
#include "AbstractService.h"

namespace server {

  /// class CommandService - 
  class CommandService : public server::AbstractService {
    // Associations
    // Attributes
  private:
    std::shared_ptr<Engine::Moteur>& moteur;
    // Operations
  public:
    CommandService (std::shared_ptr<Engine::Moteur>& m);
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus post (const Json::Value& in, int id);
    HttpStatus put (Json::Value& out, const Json::Value& in);
    HttpStatus remove (int id);
    // Setters and Getters
  };

};

#endif
