// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H

#include <map>
#include <memory>

namespace server {
  class Joueur;
}

#include "Joueur.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  protected:
    int idseq;
    std::map<int,std::unique_ptr<Joueur> > users;
    // Operations
  public:
    Game ();
    const Joueur* getUser (int id) const;
    int addUser (std::unique_ptr<Joueur> user);
    void setUser (int id, std::unique_ptr<Joueur> user);
    void removeUser (int id);
    int getNbUser () const;
    // Setters and Getters
    int getIdseq() const;
    void setIdseq(int idseq);
    const std::map<int,std::unique_ptr<Joueur> >& getUsers() const;
    void setUsers(const std::map<int,std::unique_ptr<Joueur> >& users);
  };

};

#endif
