// Generated by dia2code
#ifndef SERVER__JOUEUR__H
#define SERVER__JOUEUR__H

#include <string>

namespace server {

  /// class Joueur - 
  class Joueur {
    // Attributes
  public:
    std::string name;
    bool free;
    // Operations
  public:
    Joueur (std::string name, bool free);
    // Setters and Getters
  };

};

#endif
