// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <vector>
#include <memory>
#include <mutex>

namespace client {

  /// class Client - 
  class Client {
    // Attributes
  private:
    Engine::Moteur engine;
    std::vector<std::unique_ptr<ai::AI> > aiJoueurs;
    mutable std::mutex draw_mutex;
    // Operations
  public:
    Client ();
    void engineUpdating ();
    void engineUpdated ();
    void run ();
    // Setters and Getters
  };

};

#endif
